# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from typing import Any

from fastapi import FastAPI
from fastramqpi.events import GraphQLEvents
from fastramqpi.events import Listener
from fastramqpi.events import Namespace
from fastramqpi.main import FastRAMQPI
from fastramqpi.metrics import dipex_last_success_timestamp

from os2mo_fkk import api
from os2mo_fkk.autogenerated_graphql_client import GraphQLClient
from os2mo_fkk.config import Settings
from os2mo_fkk.database import Base
from os2mo_fkk.events import fkk_router
from os2mo_fkk.events import mo_router
from os2mo_fkk.klassifikation.api import FKKAPI
from os2mo_fkk.klassifikation.event_generator import FKK_NAMESPACE
from os2mo_fkk.klassifikation.event_generator import FKK_ROUTING_KEY
from os2mo_fkk.klassifikation.event_generator import FKKEventGenerator


def create_app() -> FastAPI:
    settings = Settings()

    fastramqpi = FastRAMQPI(
        application_name="fkk",
        settings=settings.fastramqpi,
        graphql_version=22,
        graphql_client_cls=GraphQLClient,
        database_metadata=Base.metadata,
        graphql_events=GraphQLEvents(
            # The FKK event generator sends its `change` events into this
            # namespace on MO's event system.
            declare_namespaces=[Namespace(name=FKK_NAMESPACE)],
            declare_listeners=[
                # Listen to `class` events from MO, so classes are
                # re-synchronised from FKK whenever they change in MO.
                Listener(
                    namespace="mo",
                    user_key="fkk",
                    routing_key="class",
                    path="/events/mo/class",
                ),
                # Listen to our own FKK `change` events, emitted by the event
                # generator when a Klasse changes in FKK.
                Listener(
                    namespace=FKK_NAMESPACE,
                    user_key="fkk",
                    routing_key=FKK_ROUTING_KEY,
                    path="/events/fkk/change",
                ),
            ],
        ),
    )
    fastramqpi.add_context(settings=settings)

    # FKK API
    fkk_api = FKKAPI(settings=settings.fkk)
    fastramqpi.add_context(fkk_api=fkk_api)

    # FKK event generator
    fkk_event_generator = FKKEventGenerator(
        settings=settings.fkk,
        api=fkk_api,
        graphql_client=fastramqpi.get_context()["graphql_client"],
        sessionmaker=fastramqpi.get_context()["sessionmaker"],
    )

    # The event generator controls the dipex_last_success_timestamp metric
    async def update_dipex_last_success_timestamp(_: Any) -> None:
        last_run = await fkk_event_generator.get_last_run()
        if last_run is None:
            timestamp = 0.0
        else:
            timestamp = last_run.timestamp()
        dipex_last_success_timestamp.set(timestamp)

    fastramqpi.get_context()["instrumentator"].add(update_dipex_last_success_timestamp)

    # Before the GraphQL event system
    fastramqpi.add_lifespan_manager(fkk_api, priority=500)
    # After the GraphQL event system
    fastramqpi.add_lifespan_manager(fkk_event_generator, priority=1200)

    # FastAPI router
    app = fastramqpi.get_app()
    app.include_router(api.router)
    app.include_router(mo_router)
    app.include_router(fkk_router)

    return app
