# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from typing import Annotated

from fastapi import Depends
from fastramqpi.depends import from_user_context
from fastramqpi.ramqp.depends import from_context

from os2mo_fkk.autogenerated_graphql_client import GraphQLClient as _GraphQLClient
from os2mo_fkk.klassifikation.api import FKKAPI as _FKKAPI

GraphQLClient = Annotated[_GraphQLClient, Depends(from_context("graphql_client"))]
FKKAPI = Annotated[_FKKAPI, Depends(from_user_context("fkk_api"))]
