# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any
from typing import Dict
from uuid import UUID

from .async_base_client import AsyncBaseClient
from .create_class import CreateClass
from .create_class import CreateClassClassCreate
from .delete_class import DeleteClass
from .delete_class import DeleteClassClassDelete
from .get_class import GetClass
from .get_class import GetClassClasses
from .get_facet import GetFacet
from .get_facet import GetFacetFacets
from .input_types import ClassCreateInput
from .input_types import ClassUpdateInput
from .truncate_class import TruncateClass
from .truncate_class import TruncateClassClassTerminate
from .update_class import UpdateClass
from .update_class import UpdateClassClassUpdate


def gql(q: str) -> str:
    return q


class GraphQLClient(AsyncBaseClient):
    async def get_facet(self, user_key: str, **kwargs: Any) -> GetFacetFacets:
        query = gql(
            """
            query get_facet($user_key: String!) {
              facets(filter: {user_keys: [$user_key]}) {
                objects {
                  uuid
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"user_key": user_key}
        response = await self.execute(
            query=query, operation_name="get_facet", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetFacet.model_validate(data).facets

    async def get_class(self, uuid: UUID, **kwargs: Any) -> GetClassClasses:
        query = gql(
            """
            query get_class($uuid: UUID!) {
              classes(filter: {uuids: [$uuid], from_date: null, to_date: null}) {
                objects {
                  validities(start: null, end: null) {
                    validity {
                      from
                      to
                    }
                    facet_uuid
                    uuid
                    user_key
                    name
                    parent_uuid
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"uuid": uuid}
        response = await self.execute(
            query=query, operation_name="get_class", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetClass.model_validate(data).classes

    async def create_class(
        self, input: ClassCreateInput, **kwargs: Any
    ) -> CreateClassClassCreate:
        query = gql(
            """
            mutation create_class($input: ClassCreateInput!) {
              class_create(input: $input) {
                uuid
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="create_class", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateClass.model_validate(data).class_create

    async def update_class(
        self, input: ClassUpdateInput, **kwargs: Any
    ) -> UpdateClassClassUpdate:
        query = gql(
            """
            mutation update_class($input: ClassUpdateInput!) {
              class_update(input: $input) {
                uuid
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="update_class", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateClass.model_validate(data).class_update

    async def truncate_class(
        self, uuid: UUID, **kwargs: Any
    ) -> TruncateClassClassTerminate:
        query = gql(
            """
            mutation truncate_class($uuid: UUID!) {
              class_terminate(input: {uuid: $uuid, from: "0001-01-02", to: "9999-12-30"}) {
                uuid
              }
            }
            """
        )
        variables: Dict[str, object] = {"uuid": uuid}
        response = await self.execute(
            query=query, operation_name="truncate_class", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return TruncateClass.model_validate(data).class_terminate

    async def delete_class(self, uuid: UUID, **kwargs: Any) -> DeleteClassClassDelete:
        query = gql(
            """
            mutation delete_class($uuid: UUID!) {
              class_delete(uuid: $uuid) {
                uuid
              }
            }
            """
        )
        variables: Dict[str, object] = {"uuid": uuid}
        response = await self.execute(
            query=query, operation_name="delete_class", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DeleteClass.model_validate(data).class_delete
