# Generated by ariadne-codegen
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class CreateClass(BaseModel):
    class_create: "CreateClassClassCreate"


class CreateClassClassCreate(BaseModel):
    uuid: UUID


CreateClass.model_rebuild()
