# Generated by ariadne-codegen on 2025-03-07 17:25
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class DeleteClass(BaseModel):
    class_delete: "DeleteClassClassDelete"


class DeleteClassClassDelete(BaseModel):
    uuid: UUID


DeleteClass.update_forward_refs()
DeleteClassClassDelete.update_forward_refs()
