# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List
from uuid import UUID

from .base_model import BaseModel


class GetFacet(BaseModel):
    facets: "GetFacetFacets"


class GetFacetFacets(BaseModel):
    objects: List["GetFacetFacetsObjects"]


class GetFacetFacetsObjects(BaseModel):
    uuid: UUID


GetFacet.model_rebuild()
GetFacetFacets.model_rebuild()
