# Generated by ariadne-codegen on 2026-08-17 07:03
# Source: queries.graphql

from typing import List
from uuid import UUID

from .base_model import BaseModel


class GetFacet(BaseModel):
    facets: "GetFacetFacets"


class GetFacetFacets(BaseModel):
    objects: List["GetFacetFacetsObjects"]


class GetFacetFacetsObjects(BaseModel):
    uuid: UUID


GetFacet.update_forward_refs()
GetFacetFacets.update_forward_refs()
GetFacetFacetsObjects.update_forward_refs()
