# Generated by ariadne-codegen
# Source: queries.graphql

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetClass(BaseModel):
    classes: "GetClassClasses"


class GetClassClasses(BaseModel):
    objects: List["GetClassClassesObjects"]


class GetClassClassesObjects(BaseModel):
    validities: List["GetClassClassesObjectsValidities"]


class GetClassClassesObjectsValidities(BaseModel):
    validity: "GetClassClassesObjectsValiditiesValidity"
    facet_uuid: UUID
    uuid: UUID
    user_key: str
    name: str
    parent_uuid: Optional[UUID]


class GetClassClassesObjectsValiditiesValidity(BaseModel):
    from_: Optional[datetime] = Field(alias="from")
    to: Optional[datetime]


GetClass.model_rebuild()
GetClassClasses.model_rebuild()
GetClassClassesObjects.model_rebuild()
GetClassClassesObjectsValidities.model_rebuild()
