# Generated by ariadne-codegen
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class TruncateClass(BaseModel):
    class_terminate: "TruncateClassClassTerminate"


class TruncateClassClassTerminate(BaseModel):
    uuid: UUID


TruncateClass.model_rebuild()
