# Generated by ariadne-codegen on 2024-08-08 21:31
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class TruncateClass(BaseModel):
    class_terminate: "TruncateClassClassTerminate"


class TruncateClassClassTerminate(BaseModel):
    uuid: UUID


TruncateClass.update_forward_refs()
TruncateClassClassTerminate.update_forward_refs()
